### ISSUE TITLE
[TRACKER] 4.9 current progress

### ISSUE THREAD

**Issue by SebaUbuntu** [asus-msm8937/android_kernel_asus_msm8937#1]
# X00H
- [X] Booting
- [X] Wi-Fi
- [X] Bluetooth
- [X] GPS
- [X] RIL
- [X] Camera
- [X] Audio
- [X] Sensors
- [X] Vibration
- [X] LED
- [X] USB/Charging

Display panels:
- [X] hx8394f (SebaUbuntu)
- [X] nt35521 (untested, but should work)

Touchscreen:
- [X] gt9xx (SebaUbuntu)
- [ ] ft5436
- [ ] hx852xes

Fingerprint:
- [ ] goodix_fp
- [ ] cdfinger

# X00I
- [ ] Booting
- [ ] Wi-Fi
- [ ] Bluetooth
- [ ] GPS
- [ ] RIL
- [ ] Camera
- [ ] Audio
- [ ] Sensors
- [ ] Vibration
- [ ] LED
- [ ] USB/Charging

Display panels:
- [ ] hx8394f (untested, but should work)
- [ ] nt35521 (untested, but should work)

Touchscreen:
- [ ] gt9xx
- [ ] ft5436

Fingerprint:
- [ ] goodix_fp
- [ ] focaltech
